import template from '../templates/graph-panel.html?raw';
import { defineWorkspaceSection } from './workspace-section.js';

export const GraphPanel = defineWorkspaceSection({
    name: 'GraphPanel',
    template,
    bindings: [
        'activeCapability',
        'activeConnectionId',
        'activeInput',
        'activeNode',
        'activeWebsite',
        'addNode',
        'autoLayoutGraph',
        'availableRecordingTargets',
        'browserSessionInputsReady',
        'browserTargetLabel',
        'browserTargetOpening',
        'browserTestbenchRunning',
        'changeGraphZoom',
        'deleteActiveNode',
        'deleteConnection',
        'duplicateActiveNode',
        'endStageGesture',
        'executionRunning',
        'graphLayoutRunning',
        'graphZoomPercent',
        'maximizedPanel',
        'moveStageGesture',
        'nodeMenuOpen',
        'playActiveNodeOnCurrentState',
        'playWorkflow',
        'recordingActive',
        'recordingMenuOpen',
        'recordingTargetStatus',
        'recordingTargetsAvailable',
        'recordingWorkflow',
        'resetGraphZoom',
        'startRecordingOnTarget',
        'startStageGesture',
        'stopPlayback',
        'stopRecordingWorkflow',
        't',
        'toggleNodeMenu',
        'togglePanelMaximized',
        'toggleRecordingMenu',
        'zoomFromWheel',
    ],
});
