import template from '../templates/node-editor-panel.html?raw';
import { AudioEnvelopeEditor } from './audio-envelope-editor.js';
import { defineWorkspaceSection } from './workspace-section.js';

export const NodeEditorPanel = defineWorkspaceSection({
    name: 'NodeEditorPanel',
    template,
    components: { AudioEnvelopeEditor },
    bindings: [
        'activeBrowserAction',
        'activeBrowserWait',
        'activeAudio',
        'activeAudioFileName',
        'activeCapability',
        'activeInput',
        'activeInputAcceptId',
        'activeJavaScript',
        'activeLayer',
        'activeMerge',
        'activeNode',
        'activeNodeError',
        'activeNodeLocked',
        'activeSource',
        'activeWebsite',
        'activeVideoOutput',
        'availableRecordingTargets',
        'browserTargetLabel',
        'recordingTargetStatus',
        'addInputAccept',
        'addInputPreparation',
        'availableParentLayers',
        'blurInputAccept',
        'browserSessionInputsReady',
        'browserTargetOpening',
        'deleteActiveNode',
        'editorPanelTitle',
        'executionRunning',
        'focusInputAccept',
        'formatActiveSource',
        'formattingSource',
        'handleEditorKeydown',
        'handleInputAcceptKeydown',
        'horizontalAlignment',
        'inputAcceptQueries',
        'inputAcceptSuggestions',
        'inputAcceptValues',
        'lineNumbers',
        'markActiveNodeStale',
        'markDirty',
        'markExecutionDirty',
        'maximizedPanel',
        'placementReferenceType',
        'playActiveNodeOnCurrentState',
        'removeInputAccept',
        'removeInputPreparation',
        'renderGraph',
        'selectedBrowserTarget',
        'selectorPicking',
        'setBrowserWaitCondition',
        'setHorizontalAlignment',
        'setParentLayer',
        'setPlacementReference',
        'setVerticalAlignment',
        'sourceTypes',
        'syncSourceGutter',
        't',
        'togglePanelMaximized',
        'toggleSelectorPicker',
        'updateInputFile',
        'updateInputPreparation',
        'updateBrowserWaitScript',
        'updateJavaScriptSource',
        'updateSource',
        'updateWebsiteUrl',
        'verticalAlignment',
    ],
});
