import template from '../templates/node-editor-header.html?raw';
import { defineWorkspaceSection } from './workspace-section.js';

export const NodeEditorHeader = defineWorkspaceSection({
    name: 'NodeEditorHeader',
    template,
    bindings: [
        'activeAudio',
        'activeAudioEditLocked',
        'activeBrowserAction',
        'activeDelay',
        'activeInstantAudio',
        'activeJavaScript',
        'activeLayer',
        'activeNode',
        'activeNodeError',
        'activeNodeLocked',
        'editorPanelLocked',
        'activeTextLayerLatestEnd',
        'activeVideoOutput',
        'activeWebsite',
        'audioPaused',
        'audioScrubbing',
        'audioSeekEnabled',
        'browserSessionInputsReady',
        'browserTargetOpening',
        'convertActiveTextLayer',
        'convertActiveDelay',
        'deleteActiveNode',
        'executionRunning',
        'markDirty',
        'maximizedPanel',
        'playActiveNodeOnCurrentState',
        'playNode',
        'recordingActive',
        'renderGraph',
        't',
        'togglePanelMaximized',
    ],
});
